# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.mock_with :rr

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  require_relative '../lib/vindicia-api'
  require_relative 'support/api_request_builder'

  config.before(:each) do

    # Since the Vindicia:Configuration is needed accross specs
    # Re-setting the singleton instance on each run
    Singleton.send(:__init__, Vindicia::Configuration)

    # Reset Vindicia::Class so warnings won't show up on the console
    Vindicia::API_CLASSES['4.0'].each_key do |klass_name|
      name = klass_name.to_s.capitalize.camelcase.to_sym
      Vindicia.send(:remove_const, name) if Vindicia.const_defined?(name)
    end
  end
end
